### PR TITLE
[#45] Initial try to fix module configuration not loading

### LINKED ISSUE #45: Loading module configuration do not complete
It seems like the issue occurred after upgrading the webpack in https://github.com/kbss-cvut/s-pipes-editor-ui/pull/44.

-----

It manifests as follows:
image

The console shows error:
image

Error 2 comes from the issue with s-forms that was resolved in https://github.com/kbss-cvut/s-forms/commit/0030c82472987079169abb4d5c18233d2c957f9e. 

-----

**Problem:**
It is not possible to upgrade [s-forms](https://github.com/kbss-cvut/s-forms) as it is based on `react: 18.2.0` while s-pipes-editor uses `"react": "^16.13.1"`.

**Solution:**
It is not worth making new versions of s-forms to fix the issue, but rather upgrading s-pipes-editor to `"react 18"`.

### PR DESCRIPTION
**Pull request by blcham**
Resolves #45

### CODE REVIEW

**Comment by blcham** [comment]
@palagdan 

Note, that to overcome issues with different react versions I used:
`npm install --legacy-peer-deps`

I did not investigate much, but I guess it won't be possible to fix build without upgrading react version of s-pipes-editor-ui.

**Comment by palagdan** [comment]
@blcham 

The problem was indeed in version of react. I updated it to the version 18.2.0 and everything works fine:
Screenshot from 2024-08-09 21-30-56

However, I'm not a fan of using the --legacy-peer-deps flag. While investigating the dependency issues, I discovered that many dependencies haven't been updated in years. Updating to version 18.2.0 feels like a temporary fix rather than a long-term solution.

I've created another [ticket](https://github.com/kbss-cvut/s-pipes-editor-ui/issues/49) to address the old dependencies and look for alternative libraries.

**Comment by blcham** [comment]
@palagdan is the screenshot showing how it works now? Because it looks strange ...

**Comment by palagdan** [comment]
@blcham 
 No, there are no errors in the console. I noticed that you changed a dependency for s-forms. Could the problem be related to that?

**Comment by blcham** [comment]
test it

**Comment by palagdan** [comment]
@blcham 
I investigated this problem and what I got:

## Before updating React to version 18:

The "Error Loading SForms..." message appears in all examples except for the Hello-World example.
When attempting to call the loading module configuration in the examples where it fails, the response from S-Forms appears valid and should work, but it does not.

Screenshot from 2024-08-11 11-59-33
In the Hello-World example, which is the only one where it works, submitting the form results in a request that is missing parameters (firstName, lastName), leading to an error.
Screenshot from 2024-08-11 11-26-02

## After I updated react to version 18:
The infinite "Loading SForms" error no longer occurs, but the form is still not working correctly as it fails to send the parameters in the request.

**Comment by palagdan** [comment]
@blcham 
I also investigated the issues with the incorrect forms and found some unusual results. Initially, I tested different [packages](https://github.com/kbss-cvut/s-pipes-editor-ui/pkgs/container/s-pipes-editor-ui%2Fs-pipes-editor-ui/versions?filters%5Bversion_type%5D=tagged) and observed varying outcomes. At first, the Hello-World example returned the correct forms, while the other examples did not. I tested with different Docker builds, including ones published a year ago. However, when I tried the latest build, all forms were correct in all examples, except for the constraint validation example, which initially returned an incorrect form but then corrected itself after a few minutes. I’m quite confused by these inconsistencies. Could we review this together?

**Pull request merged**
